# Generated by Django 3.0.7 on 2020-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mobilenumber',
            field=models.IntegerField(default='0'),
        ),
    ]
