# Generated by Django 3.0.7 on 2021-02-27 06:19

from django.db import migrations, models
# import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopdetail',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_addr', models.CharField(default='', max_length=500)),
                ('shop_city', models.CharField(default='', max_length=100)),
                ('shop_state', models.CharField(default='', max_length=50)),
                ('shop_zip_code', models.CharField(default='', max_length=50)),
                # ('shop_mobilenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('shop_email', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
