# Generated by Django 3.0.7 on 2021-02-27 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shopdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='shop.Shopdetail'),
        ),
    ]
