# Generated by Django 3.0.7 on 2021-02-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(default=101, editable=False, on_delete=django.db.models.deletion.CASCADE, to='shop.Shopdetail'),
        ),
    ]
