# Generated by Django 4.2.5 on 2023-10-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210227_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='mobilenumber',
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='shop.shopdetail'),
        ),
    ]
